version: '3'
services:
    web:
        build: .
        command: bash -c "sleep 15 && make setup-python && ls && python server.py"
        ports:
            - "5000:5000"
        environment:
            - TZ=America/Sao_Paulo